name: Cypress Tests - Basic Dapp

on:
  pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: basic-dapp
          build: yarn
          start: yarn start:cypress
          record: false
          wait-on-timeout: 120
          wait-on: 'http://localhost:3000'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
